//
//  NetworkCommunicationDefinitions.h
//  
//
//  Created by Chris Martinez on 9/26/13.
//
//

#ifndef _NetworkCommunicationDefinitions_h
#define _NetworkCommunicationDefinitions_h

// basic success or failure check
#define NETWORK_COMMUNICATION_FAIL 0
#define NETWORK_COMMUNICATION_SUCCESS 1

#define NETWORK_COMMUNICATION_STATUS_OK 200
#define NETWORK_COMMUNICATION_STATUS_CREATED 201
#define NETWORK_COMMUNICATION_STATUS_NO_CONTENT 204
#define NETWORK_COMMUNICATION_STATUS_BAD_REQUEST 400
#define NETWORK_COMMUNICATION_STATUS_AUTHORIZATION_REQUIRED 401
#define NETWORK_COMMUNICATION_STATUS_FORBIDDED 403
#define NETWORK_COMMUNICATION_STATUS_NOT_FOUND 404
#define NETWORK_COMMUNICATION_STATUS_TIMEOUT 408
#define NETWORK_COMMUNICATION_STATUS_INTERNAL_ERROR 500
#define NETWORK_COMMUNICATION_STATUS_UNAVAILABLE 503

#endif
